// Code Generated by Sidekick is for learning and experimentation purposes only.
package locatorsfile;

import net.serenitybdd.core.pages.PageObject;
import net.thucydides.core.pages.WebElementFacade;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

import java.util.List;

public class LoginPage extends PageObject {

    @FindBy(id = "Email")
    WebElement txt_username;

    @FindBy(id = "Password")
    WebElement txt_Password;

    @FindBy(xpath = "//div[@class='buttons']/input[@type='submit']")
    WebElement loginbtn;


    @FindBy(linkText = "Books")
    WebElement books;

    @FindBy(linkText = "Computing and Internet")
    WebElement Computing_and_Internet;

    @FindBy(linkText = "Add your review")
    WebElement addingReview;

    @FindBy(id = "AddProductReview_Title")
    WebElement AddProductReview_Title;

    @FindBy(id = "AddProductReview_ReviewText")
    WebElement AddProductReview_ReviewTexte;

    @FindBy(id = "addproductrating_5")
    WebElement Rating;

    @FindBy(name = "add-review")
    WebElement submitReview;

    @FindBy(xpath = "//div[@class='product-review-item']")
    public List<WebElementFacade> bookTitles;


    public void openLoginPage() {
        openUrl("https://demowebshop.tricentis.com/login");
        getDriver().manage().window().maximize();
    }

    public void enterUsername(String username) {
        txt_username.sendKeys(username);
    }

    public void enterPassword(String password) {
        txt_Password.sendKeys(password);
    }

    public void clickLogin() {
        loginbtn.click();
    }

    public void clickBooks() {
        books.click();
    }

    public void click_Computing_and_Internet() {
        Computing_and_Internet.click();
    }

    public void addReview() {
        addingReview.click();
    }

    public void AddProductReview_Title(String AddProductReview) {
        AddProductReview_Title.sendKeys(AddProductReview);
    }

    public void AddProductReview_ReviewText(String AddProductReview_ReviewTex1t) {
        AddProductReview_ReviewTexte.sendKeys(AddProductReview_ReviewTex1t);
    }

    public void rating_of_book() {
        Rating.click();
    }

    public void submit_review() {


        submitReview.click();
    }

    public String getLastReviewTitle() {
        WebElementFacade lastElement = bookTitles.get(bookTitles.size() - 1);
        System.out.println(lastElement);
        return lastElement.findBy(By.cssSelector(".review-title")).getText();
    }

    public String getLastReviewText() {
        WebElementFacade lastElement = bookTitles.get(bookTitles.size() - 1);
        return lastElement.findBy(By.cssSelector(".review-text")).getText();
    }


}
