// Code Generated by Sidekick is for learning and experimentation purposes only.
package locatorsfile;


import net.serenitybdd.annotations.Steps;

public class LoginSerenitySteps {
    LoginPage loginPage;

    public void loginUser() {
        loginPage.openLoginPage();
        loginPage.enterUsername("omkar1234512345@gmail.com");
        loginPage.enterPassword("123456");
        loginPage.clickLogin();
    }
}
